version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebcursos_platform
      MYSQL_USER: ebcursos
      MYSQL_PASSWORD: ebcursos123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
